# Generated by Django 4.1.13 on 2024-03-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Info',
        ),
    ]
