# Generated by Django 5.0.3 on 2024-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0003_info_predictions_alter_info_age_alter_info_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="education",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Diploma"),
                    (1, "Graduation"),
                    (2, "Post-Graduation"),
                    (3, "Undergraduation"),
                ],
                null=True,
            ),
        ),
    ]
