# Generated by Django 5.0.3 on 2024-04-12 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0004_alter_info_education"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="info",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="info",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
