# Generated by Django 5.0.3 on 2024-04-12 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base", "0005_alter_info_options_info_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(16),
                    django.core.validators.MaxValueValidator(35),
                ],
            ),
        ),
    ]
